[project]
name = "pycentroid"
version = "1.0.1"
authors = [
  { name="Kyriakos Barbounakis", email="k.barbounakis@gmail.com" },
]
description = "@themost-framework for python"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/centroid-py/centroid"
"Bug Tracker" = "https://github.com/centroid-py/centroid/issues"